#!/bin/bash -e

# install openjdk7 by default
sudo apt-get -y install openjdk-7-jdk

# install commonly used Java build tools
sudo apt-get -y install ant ant-contrib ivy maven

# install utility that allows us to switch JDK versions
sudo apt-get -y install default-jdk

# Download gradle

pushd /tmp

# download + decompress grade
wget https://services.gradle.org/distributions/gradle-1.12-bin.zip --quiet
unzip -q gradle-1.12-bin.zip

# install
sudo mv gradle-1.12 /usr/local
sudo chown -R ubuntu:ubuntu /usr/local/gradle-1.12
chmod +x /usr/local/gradle-1.12/bin/gradle

# cleanup
rm gradle-1.12-bin.zip

popd
